-- Core profiles table
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text default 'user',
  plan_id text default 'trial',
  created_at timestamp with time zone default now()
);

-- Releases table for desktop downloads
create table if not exists public.releases (
  id bigint generated by default as identity primary key,
  version text not null,
  platform text not null check (platform in ('win', 'mac')),
  url text not null,
  notes text,
  is_latest boolean default false,
  created_at timestamp with time zone default now()
);

-- Auto-create profile on auth user creation
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.releases enable row level security;

-- Profiles policies
create policy "Profiles are viewable by owner"
  on public.profiles
  for select
  using (auth.uid() = id);

create policy "Profiles are updatable by owner"
  on public.profiles
  for update
  using (auth.uid() = id);

create policy "Admins can manage profiles"
  on public.profiles
  for all
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

-- Releases policies
create policy "Releases are viewable"
  on public.releases
  for select
  using (true);

create policy "Admins can manage releases"
  on public.releases
  for all
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );
